// Skill names enum
export const SkillNames = {
  PHOTOSHOP: "photoshop",
  ILLUSTRATOR: "illustrator",
  FIGMA: "figma",
  BLENDER: "blender",
  CLIP_STUDIO_PAINT: "clipstudiopaint",
  AFTER_EFFECTS: "aftereffects",
  CANVA: "canva",
  WORD: "word",
  EXCEL: "excel",
  POWERPOINT: "powerpoint",
  PREMIERE_PRO: "premierepro",
  AUDITION: "audition",
};

// Skill type (for reference)
// id: number, name: string, label: string, shortDescription: string, color: string, icon: string

export const SKILLS = {
  [SkillNames.PHOTOSHOP]: {
    id: 1,
    name: SkillNames.PHOTOSHOP,
    label: "Photoshop",
    shortDescription: "Software de edición de imágenes y diseño gráfico.",
    color: "#31A8FF",
    icon: "/assets/Photoshop Logo.png",
  },
  [SkillNames.ILLUSTRATOR]: {
    id: 2,
    name: SkillNames.ILLUSTRATOR,
    label: "Illustrator",
    shortDescription: "Software de diseño de gráficos vectoriales.",
    color: "#FF9A00",
    icon: "/assets/Illustrator Logo.png",
  },
  [SkillNames.FIGMA]: {
    id: 3,
    name: SkillNames.FIGMA,
    label: "Figma",
    shortDescription: "Herramienta de diseño de interfaces y prototipado.",
    color: "#F24E1E",
    icon: "/assets/tech/figma.svg",
  },
  [SkillNames.BLENDER]: {
    id: 4,
    name: SkillNames.BLENDER,
    label: "Blender",
    shortDescription: "Software de modelado, animación y renderizado 3D.",
    color: "#E87D0D",
    icon: "/assets/tech/blender.svg",
  },
  [SkillNames.CLIP_STUDIO_PAINT]: {
    id: 5,
    name: SkillNames.CLIP_STUDIO_PAINT,
    label: "Clip Studio Paint",
    shortDescription: "Software para ilustración, cómic y animación.",
    color: "#1898E6",
    icon: "/assets/Clip Studios Logo.png",
  },
  [SkillNames.AFTER_EFFECTS]: {
    id: 6,
    name: SkillNames.AFTER_EFFECTS,
    label: "After Effects",
    shortDescription: "Software de motion graphics y efectos visuales.",
    color: "#9999FF",
    icon: "/assets/After Logo.png",
  },
  [SkillNames.CANVA]: {
    id: 7,
    name: SkillNames.CANVA,
    label: "Canva",
    shortDescription: "Plataforma de diseño gráfico simplificado.",
    color: "#00C4CC",
    icon: "/assets/tech/canva.svg",
  },
  [SkillNames.WORD]: {
    id: 8,
    name: SkillNames.WORD,
    label: "Word",
    shortDescription: "Procesador de textos de Microsoft Office.",
    color: "#2B579A",
    icon: "/assets/Word Logo.png",
  },
  [SkillNames.EXCEL]: {
    id: 9,
    name: SkillNames.EXCEL,
    label: "Excel",
    shortDescription: "Hoja de cálculo de Microsoft Office.",
    color: "#217346",
    icon: "/assets/Excel Logo.png",
  },
  [SkillNames.POWERPOINT]: {
    id: 10,
    name: SkillNames.POWERPOINT,
    label: "PowerPoint",
    shortDescription: "Software de presentaciones de Microsoft Office.",
    color: "#B7472A",
    icon: "/assets/Power Point Logo.png",
  },
  [SkillNames.PREMIERE_PRO]: {
    id: 11,
    name: SkillNames.PREMIERE_PRO,
    label: "Premiere Pro",
    shortDescription: "Software de edición de video profesional.",
    color: "#9999FF",
    icon: "/assets/Premiere Pro Logo.png",
  },
  [SkillNames.AUDITION]: {
    id: 12,
    name: SkillNames.AUDITION,
    label: "Audition",
    shortDescription: "Software de edición y postproducción de audio.",
    color: "#9999FF",
    icon: "/assets/Audition Logo.png",
  },
};
